platform :ios, 9.0

use_frameworks!
inhibit_all_warnings!

target 'HCaptcha_Example' do
  pod 'HCaptcha/RxSwift', :path => '../'
  pod 'RxCocoa', '~> 6.2.0'
  pod 'SwiftLint', '~> 0.33'

  target 'HCaptcha_Tests' do
    inherit! :search_paths

    pod 'AppSwizzle', '~> 1.3'
    pod 'RxBlocking', '~> 6.2.0'
  end

  target 'HCaptcha_UITests' do
    inherit! :search_paths
  end
end

post_install do |i|
  target = File.join(Dir.pwd, "../.git/hooks/pre-push")
  unless File.symlink?(target)
    puts "Installing git hook for pre-push"

    begin
      File.symlink(File.join(Dir.pwd, "../pre-push.sh"), target)
    rescue => exc
    end
  end
end
